[tools]
# Infrastructure
terraform = "1.12"
terragrunt = "0.80"
ansible = "latest"
dagger = "latest"
infisical = "latest"
step = "latest"

# Languages & Runtimes
go = "latest"
uv = "latest"

# Kubernetes
argocd = "latest"
colima = "latest"
kubectl = "latest"
kustomize = "latest"
helm = "latest"
helmfile = "latest"
k9s = "latest"
krew = "latest"
kubecolor = "latest"
kubeseal = "latest"
minikube = "latest"
stern = "latest"
talosctl = "latest"
timoni = "latest"
istioctl = "1.27"

# Development
golangci-lint = "latest"
pre-commit = "latest"
actionlint = "latest"
terraform-docs = "latest"
tflint = "latest"
direnv = "latest"
lazygit = "latest"
pipx = "latest"
prettier = "latest"
restish = "latest"

# CLI Tools
bat = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
glab = "latest"
granted = "latest"
jq = "latest"
ripgrep = "latest"
starship = "latest"
viddy = "latest"
yq = "latest"
yt-dlp = "latest"
cosign = "latest"
copier = "latest"
dapr = "latest"
node = "25"
# NOTE: Use the native install of claude-code

[settings]
idiomatic_version_file_enable_tools = ["go"]
