[general]
# Documentation: https://alacritty.org/config-alacritty.html
live_config_reload = true
import = [
  # "~/.config/alacritty/themes/themes/omakub.toml",
  # "~/.config/alacritty/themes/themes/rose_pine.toml",
  "~/.config/alacritty/themes/themes/tokyo_night_enhanced.toml",
]

[window]
position = "None"
decorations = "Buttonless"
blur = false
startup_mode = "Maximized"
option_as_alt = "OnlyLeft"
padding.x = 10
padding.y = 10
dynamic_padding = true
dynamic_title = true

[cursor]
thickness = 0.35
unfocused_hollow = true

[cursor.style]
shape = "Block"

[font]
size = 20
builtin_box_drawing = true

[font.normal]
# family = "PragmataPro Mono Liga"
family = "PragmataPro VF Mono Liga"

[terminal]
shell = "/opt/homebrew/bin/fish"

[keyboard]
[[keyboard.bindings]]
key = "\\"
mods = "Alt"
action = "ToggleFullscreen"

[[keyboard.bindings]]
key = "}"
mods = "Command"
action = "SelectNextTab"

[[keyboard.bindings]]
key = "{"
mods = "Command"
action = "SelectPreviousTab"


